services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      app-blue:
        condition: service_healthy

  app-blue: &app-common
    container_name: app-blue
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - app-blue:latest
    image: app-blue:latest
    environment:
      TZ: "Europe/Warsaw"
    restart: always
    stop_signal: SIGTERM
    stop_grace_period: 30s
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 5s
    command: ["./main"]


  app-green:
    <<: *app-common
    container_name: app-green
    restart: unless-stopped
    build:
      tags:
        - app-green:latest
    image: app-green:latest

networks:
  app-network:
    driver: bridge
