name: Auto-deploy


on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ master ]
    types:
      - completed
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'deploy-add' }}
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/StravaTracker
            /home/ubuntu/StravaTracker/set-up-script.sh