name: Deploy to server

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'deploy-add' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Create .env file
      run: |
        echo "STRAVA_CLIENT_ID=${{ secrets.STRAVA_CLIENT_ID }}" >> .env
        echo "STRAVA_CLIENT_SECRET=${{ secrets.STRAVA_CLIENT_SECRET }}" >> .env
        echo "STRAVA_REFRESH_TOKEN=${{ secrets.STRAVA_REFRESH_TOKEN }}" >> .env
        echo "STRAVA_CLUB_ID=${{ vars.STRAVA_CLUB_ID }}" >> .env

        echo "DB_URI=${{ secrets.DB_URI }}" >> .env
        echo "DB_URI=${{ secrets.DB_NAME }}" >> .env

    - name: Copy .env and project files to server
      run: |
        scp -r -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/strava/.env
        scp -r -o StrictHostKeyChecking=no . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/strava

    - name: Deploy on server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        cd /home/${{ secrets.SSH_USER }}/strava
        docker-compose down
        docker-compose up -d --build
        EOF