name: Zero downtime deployment

on:
  workflow_run:
    workflows: [ "Run Tests" ]
    branches: [ master ]
    types: [completed]

jobs:
  deploy:
    if: >
      ${{
        github.event.workflow_run.conclusion == 'success' &&
        github.event.workflow_run.event == 'push'
      }}
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Connect via ssh and run script
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/StravaTracker
            /home/ubuntu/StravaTracker/scripts/zero-downtime-deploy.sh